### ISSUE TITLE
ActiveRecord Querying

### ISSUE THREAD

**Issue by Ricardonacif** [codescrum/active_poro#1]
Hey,

Would you think it is valuable to add querying to the gem like `user.where(name: 'John')`? I'm considering a PR.

Thanks,

**Comment by gato-omega** [comment]
Hi there!

Thank you for checking out the gem!
The main purpose of this gem is to have active_record -like associations,
and its currently limited to that purpose.

I think there are already other gems such as [rom](https://github.com/rom-rb/rom) which may be the one's you are looking for.

I have had the idea to just rename this gem to be
"active_poro-associations" so that the functionality that it provides goes
better with the actual name, and have "active_poro" as a meta-package or
container gem which could incorporate any other features.

This was mainly a project emerged from the need of bidirectional in-memory
associations (sometimes needed in configuration scenarios) and it was kind
of written as a proof of concept. If you would like to add querying I would
suggest perhaps forking this repo and incorporating them separately
(perhaps active_poro-querying), the idea would be that the gems can be used
in little projects and simple scripts independently.

On Sat, May 23, 2015 at 1:37 PM, Ricardo Nacif notifications@github.com
wrote:

> Hey,
> 
> Would you think it is valuable to add querying to the gem like user.where(name:
> 'John')? I'm considering a PR.
> 
> Thanks,
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/codescrum/active_poro/issues/1.

## 

_Miguel Diaz_
- ​​                             *
  _Code_*Scrum   *

***_Confidentiality Notice_: This e-mail message, including any
attachments, is for the sole use of the intended recipient(s) and may
contain confidential and privileged information. Any unauthorized review,
use, disclosure or distribution is prohibited. If you are not the intended
recipient, please contact the sender by reply e-mail and destroy all copies
of the original message.***

**Comment by Ricardonacif** [comment]
Thanks for the answer, I got your point, and I have forgot about rom. It really doesn't make much sense. Closing this issue.
